### ISSUE TITLE
Collections: Updating display names

### ISSUE THREAD

**Issue by asizemore** [VEuPathDB/ApiCommonData#12]
Currently the taxonomic category names are very long and include more information than necessary. For example, "Relative abundance of order data". In the subsetting tab we already have the information that it's relative abundance, and when the user selects it for the app it also says 16S along with it. So it seems that the "relative abundance" and "data" parts of the display name are unnecessary. 

<img width="377" alt="Screen Shot 2022-04-27 at 1 08 42 PM" src="https://user-images.githubusercontent.com/11710234/165583821-d4e2c346-c330-40ad-ac47-d5d0ffaac661.png">

Could we please change the display names of these to the taxonomic levels, like how it is on the live site? 

Note this is also very helpful for the ranked abundance app, where the display name gets used as an axis name (see below).
<img width="850" alt="Screen Shot 2022-04-27 at 1 09 26 PM" src="https://user-images.githubusercontent.com/11710234/165581612-d714e918-d121-4f25-a564-59209bb0ee04.png">

**Comment by asizemore** [comment]
Worth doing when alongside reordering based on taxa

**Comment by danicahelb** [comment]
@nkittur-uga and @zhengj2007 please work with @asizemore and @dpbisme to update display names

**Comment by nkittur-uga** [comment]
Ann has confirmed that this work has already been done.

**Comment by asizemore** [comment]
yup! Looks good on the site. Closing issue.
