### ISSUE TITLE
CORRAL results: update names

### ISSUE THREAD

**Issue by asizemore** [VEuPathDB/ApiCommonData#13]
Currently it's called "Data item". What should we call it instead?

**Comment by asizemore** [comment]
Decided to have it read "Eukaryote detection and abundance analysis". Jie asked for a github issue in their tracking system, so i made one [here](https://github.com/VEuPathDB-ontology/VEuPathDB-ontology/issues/392)

**Comment by asizemore** [comment]
Update - the [issue](https://github.com/VEuPathDB-ontology/VEuPathDB-ontology/issues/392) is now assigned to @johnwjudkins . See the linked issue to follow status updates.

**Comment by danicahelb** [comment]
@asizemore can we close this ticket as https://github.com/VEuPathDB-ontology/VEuPathDB-ontology/issues/392 is now closed?

**Comment by asizemore** [comment]
Yup! Now called Microbial Eukaryote Analysis
